name: Build and Release

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.12.0
    - name: Build
      run: python3 build.py --all
    - uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: ./release.zip
